export const SERVICE_PENDING = 'service_pending'
export const SERVICE_ERROR = 'service_error'
export const SERVICE_SUCCESS = 'service_success'
export const FAVOURITES_DATA = 'favourites_data'
export const F_DATA = 'f_data'